# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: yujinoh
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: project-server
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-project-server

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.10
  region : ap-northeast-2
  ecr:
    images:
      appimage:
        path: ./

functions:
  app:
    image:
      name : appimage
    timeout : 120
    events:
      - httpApi: '*'

package:
  individually: true
  exclude:
    - node_modules/**  # node_modules 폴더와 그 하위 모든 파일 및 디렉토리 제외
    - .git/**  # .git 폴더와 그 하위 모든 파일 및 디렉토리 제외
    - tests/**  # tests 폴더와 그 하위 모든 파일 및 디렉토리 제외
  include:
    - src/**  # src 폴더와 그 하위 모든 파일 및 디렉토리 포함
    - handler.py  # 루트 디렉토리의 handler.py 파일 포함
    - config/**  # config 폴더와 그 하위 모든 파일 및 디렉토리 포함