# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: onmyway
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: joyfulmind-app
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-joyfulmind-app

provider:
  name: aws
  runtime: python3.10
  region: ap-northeast-2
  profile: api_dev

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

custom:
  wsgi:
    app: app.app
  pythonRequirements:
    dockerizePip: true  # Docker 사용 설정
    useStaticCache: false
    slim: true
    strip: false

plugins:
  - serverless-wsgi
  - serverless-python-requirements

package:
  individually: true
  exclude:
    - node_modules/**
    - .git/**
    - tests/**
    - "**/*.csv"
  include:
    - src/**
    - handler.py
    - config/**
    - sbert_model/**
    - data/**
